# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3702a46d1f65c062d91b9257bfbf1e17e3caf454a66f97a4a3d966120a75741d7aefac5f4a9dacae1f3d211c41365047677c57dcff77280582812d9f97886634

test:
  secret_key_base: 686dadc3d51b477b6b31f58bb6a968b5bc4aae42aa2face52a7b3348be71ecf8e0dee43932af236230c60e4bb09f544113d320bf016581608805f11c4b24463c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
